[workspace]
members = ["surrounded", "tygydyk"]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
bevy = { version = "0.13" }
thiserror = { version = "1" }
