[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
bevy_editor_pls.workspace = true
thiserror.workspace = true

leafwing-input-manager = { version = "0.11" }