[package]
name = "surrounded"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
bevy_editor_pls.workspace = true
leafwing-input-manager.workspace = true

bevy_pkv = { version = "0.9" }
bevy_rapier3d = { version = "0.23" }
